#!/usr/bin/env bash


# Load RVM, if you are using it
[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm

# Add rvm gems and nginx to the path
export PATH=$PATH:~/.gem/ruby/1.8/bin:/opt/nginx/sbin
export PATH=$PATH:/usr/local/opt/ruby/bin

# Add rbenv to the path, /usr/local/bin for Homebrew files first
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
export PATH=/usr/local/bin:$PATH

# Path to the bash it configuration
export BASH_IT=$HOME/.bash_it

# Path to the VMD and NAMD applications
export PATH=$PATH:/Applications/VMD\ 1.9.1.app/Contents/Resources/VMD.app/Contents/MacOS
export PATH=$PATH:/Applications/NAMD_2.9_MacOSX-x86_64-multicore

# General aliases
alias l="ls -alF"
alias sl=ls
alias ls='ls -G'        # Compact view, show colors
alias la='ls -AF'       # Compact view, show hidden
alias ll='ls -al'
alias l1='ls -1'

# On Crunchbang Linux, emulate the OS X 'open in Finder' option
# alias open='xdg-open'   
# alias ls='ls --color'        # Compact view, show colors

# Large History File Size
HISTFILESIZE=100000

# Alias valgrind options for fun
alias vf='valgrind -q --track-origins=yes --leak-check=full \
                      --show-reachable=yes --db-attach=yes'
alias vn='valgrind -q --track-origins=yes --leak-check=full \
                      --db-attach=yes'
alias valgrind='valgrind -q'

# Directory
alias md='mkdir -p'
alias rd='rmdir'
alias h='history | tail'

# Make a directory and cd to it
function mkcd
{
   dir="$*";
   mkdir -p "$dir" && cd "$dir";
}

# Move a file and cd to newdir
function mvcd 
{
   if [ $# -ne 2 -o -d $2 ]; then
      mv "$@"       # Move the files to the dir
      while [ $# -gt 1 ]; do shift; done
      cd "$1"       # Shift until end, change to dir
   else
      echo "mvcd: Last argument should be directory" 1>&2
      return 1
   fi
}

# Lock and Load a custom theme file
# location /.bash_it/themes/
# export BASH_IT_THEME='clean'||'nwinkler'||'pete'||'standard'
export BASH_IT_THEME='cleanpete'

# Your place for hosting Git repos. I use this for private repos.
export GIT_HOSTING='git@git.domain.com'

# Set my editor and git editor
export EDITOR="/usr/local/bin/vim"
export GIT_EDITOR='/usr/local/bin/vim'

# Set the path nginx
export NGINX_PATH='/opt/nginx'

# Don't check mail when opening terminal.
unset MAILCHECK

# Change this to your console based IRC client of choice.
export IRC_CLIENT='irssi'

# Set this to the command you use for todo.txt-cli
export TODO="t"

# Set vcprompt executable path for scm advance info in prompt (demula theme)
# https://github.com/xvzf/vcprompt
#export VCPROMPT_EXECUTABLE=~/.vcprompt/bin/vcprompt

# Load Bash It
source $BASH_IT/bash_it.sh

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
