#!/usr/bin/env bash


# Load RVM, if you are using it
[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm

# Add rvm gems and nginx to the path
export PATH=$PATH:~/.gem/ruby/1.8/bin:/opt/nginx/sbin

# Path to the bash it configuration
export BASH_IT=$HOME/.bash_it

# Path to the VMD and NAMD applications
export PATH=$PATH:/Applications/VMD\ 1.9.1.app/Contents/Resources/VMD.app/Contents/MacOS
export PATH=$PATH:/Applications/NAMD_2.9_MacOSX-x86_64-multicore

# General aliases
alias l="ls -alF"
alias sl=ls
alias ls='ls -G'        # Compact view, show colors
alias la='ls -AF'       # Compact view, show hidden
alias ll='ls -al'
alias l1='ls -1'
# On Crunchbang Linux, emulate the OS X 'open in Finder' option
# alias open='xdg-open'   

# Directory
alias md='mkdir -p'
alias rd='rmdir'
alias h='history | tail'

# Make a directory and cd to it
function mkcd
{
   dir="$*";
   mkdir -p "$dir" && cd "$dir";
}

# Lock and Load a custom theme file
# location /.bash_it/themes/
# export BASH_IT_THEME='clean'||'nwinkler'||'pete'||'standard'
export BASH_IT_THEME='cleanpete'

# Your place for hosting Git repos. I use this for private repos.
export GIT_HOSTING='git@git.domain.com'

# Set my editor and git editor
export EDITOR="/usr/bin/mate -w"
export GIT_EDITOR='/usr/bin/mate -w'

# Set the path nginx
export NGINX_PATH='/opt/nginx'

# Don't check mail when opening terminal.
unset MAILCHECK

# Change this to your console based IRC client of choice.
export IRC_CLIENT='irssi'

# Set this to the command you use for todo.txt-cli
export TODO="t"

# Set vcprompt executable path for scm advance info in prompt (demula theme)
# https://github.com/xvzf/vcprompt
#export VCPROMPT_EXECUTABLE=~/.vcprompt/bin/vcprompt

# Load Bash It
source $BASH_IT/bash_it.sh
