" http://vimdoc.sourceforge.net/htmldoc/starting.html#vimrc

set nocompatible        " use vim defaults
set scrolloff=3         " keep 3 lines when scrolling
set ai                  " set auto-indenting on for programming

set showcmd             " display incomplete commands
set nobackup            " do not keep a backup file
set number              " show line numbers
set ruler               " show the current row and column

set hlsearch            " highlight searches
hi Search ctermbg=LightYellow
hi Search ctermfg=Red
" *cterm-colors*
"
" NR-16   NR-8    COLOR NAME
" 0       0       Black
" 1       4       DarkBlue
" 2       2       DarkGreen
" 3       6       DarkCyan
" 4       1       DarkRed
" 5       5       DarkMagenta
" 6       3       Brown, DarkYellow
" 7       7       LightGray, LightGrey, Gray, Grey
" 8       0*      DarkGray, DarkGrey
" 9       4*      Blue, LightBlue
" 10      2*      Green, LightGreen
" 11      6*      Cyan, LightCyan
" 12      1*      Red, LightRed
" 13      5*      Magenta, LightMagenta
" 14      3*      Yellow, LightYellow
" 15      7*      White

set incsearch           " do incremental searching
set showmatch           " jump to matches when entering regexp
set noignorecase        " ignore case when searching
set smartcase           " no ignorecase if Uppercase char present

set visualbell t_vb=    " turn off error beep/flash
set novisualbell        " turn off visual bell

set backspace=indent,eol,start  " make that backspace key work the way it should

syntax on               " turn syntax highlighting on by default
" filetype on             " detect type of file
" filetype indent on      " load indent file for specific file type

set smartindent
set tabstop=2
set shiftwidth=2
set expandtab         " tabs to spaces

set t_RV=               " http://bugs.debian.org/608242, http://groups.google.com/group/vim_dev/browse_thread/thread/9770ea844cec3282

" When encrypting any file, use the much stronger blowfish algorithm
set cryptmethod=blowfish

" Disables additional files [swap files, backups], prevents dangerous shell commands, and prevents history
autocmd BufReadPost * if &key != "" | set noswapfile nowritebackup viminfo= nobackup noshelltemp history=0 secure | endif

" execute pathogen#infect()

set re=2 " https://github.com/fatih/vim-go/issues/3171

syntax enable
" set background=dark
" set background=light
" colorscheme solarized

" filetype off
" filetype plugin indent off
" set rtp+=$GOROOT/misc/vim
" filetype plugin indent on
" syntax on

"if has("autocmd")
  "augroup ruby
    "au BufReadPre,FileReadPre set kp=ri sw=2 ts=2 expandtab
  "augroup END
"endif

